// <auto-generated />
using BreakfastMasterAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BreakfastMasterAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240610140119_UserBreadRollEntity")]
    partial class UserBreadRollEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BreakfastMasterAPI.Models.BreadRollModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BreadRolls");
                });

            modelBuilder.Entity("BreakfastMasterAPI.Models.GroupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("BreakfastMasterAPI.Models.UserBreadRoll", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("BreadRollId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("UserId", "BreadRollId");

                    b.HasIndex("BreadRollId");

                    b.ToTable("UserBreadRolls");
                });

            modelBuilder.Entity("BreakfastMasterAPI.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BreakfastMasterAPI.Models.UserBreadRoll", b =>
                {
                    b.HasOne("BreakfastMasterAPI.Models.BreadRollModel", "BreadRoll")
                        .WithMany("UserBreadRolls")
                        .HasForeignKey("BreadRollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BreakfastMasterAPI.Models.UserModel", "User")
                        .WithMany("UserBreadRolls")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BreadRoll");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BreakfastMasterAPI.Models.UserModel", b =>
                {
                    b.HasOne("BreakfastMasterAPI.Models.GroupModel", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BreakfastMasterAPI.Models.BreadRollModel", b =>
                {
                    b.Navigation("UserBreadRolls");
                });

            modelBuilder.Entity("BreakfastMasterAPI.Models.GroupModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BreakfastMasterAPI.Models.UserModel", b =>
                {
                    b.Navigation("UserBreadRolls");
                });
#pragma warning restore 612, 618
        }
    }
}
